FILES = ProducerConsumer.java Buffer.java Consumer.java Producer.java
all:
	javac -g $(FILES)
run:
	java ProducerConsumer
clean:
	rm -f ./*.class ./*.zip
package:
	zip -r Henry-Lewis-HW4.zip $(FILES) Makefile README.txt